name: 'purecloud'
version: '1.0'

source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]

models:
    purecloud:
    transform:
      materialized: table
    base:
      materialized: ephemeral
    vars:
      activity_code_table: purecloud.activity_code
      conversation_table: purecloud.conversation
      conversation_participants_table: purecloud.conversation__participants
      conversation_participants_sessions_table: purecloud.conversation__participants__sessions
      conversation_participants_sessions_segments_table: purecloud.conversation__participants__sessions__segments
      groups_table: purecloud.groups
      location_table: purecloud.location
      mangagement_unit_table: purecloud.mangagement_unit
      management_unit_users_table: purecloud.management_unit_users
      presence_status_table: purecloud.presence
      queue_table: purecloud.queues
      queue_membership_table: purecloud.queue_membership
      queue_wrapup_code_table: purecloud.queue_wraup_code
      user_schedule_table: purecloud.user_schedule
      user_schedule_shifts_table: purecloud.user_schedule__shifts
      user_schedule_shifts_activities_table: purecloud.user_schedule__shifts__activities
      user_state_table: purecloud.user_state
      users_table: purecloud.users
      users_locations_table: purecloud.users__locations

profile: simba