name: 'purecloud'
version: '1.0'

source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]

profile: dev

models:
  purecloud:
    base:
      materialized: ephemeral
    vars:
      # activity_code_table: # schema.activity_code
      # conversation_table: # schema.conversation
      # conversation__participants_table: # schema.conversation__participants
      # conversation__participants__sessions_table: # schema.conversation__participants__sessions
      # conversation__participants__sessions__segments_table: # schema.conversation__participants__sessions__segments
      # groups_table: # schema.groups
      # location_table: # schema.location
      # mangagement_unit_table: # schema.mangagement_unit
      # management_unit_users_table: # schema.management_unit_users
      # presence_status_table: # schema.presence_status
      # user_schedule_table: # schema.user_schedule
      # user_schedule__shifts_table: # schema.user_schedule__shifts
      # user_schedule__shifts__activities_table: # schema.user_schedule__shifts__activities
      # user_state_table: # schema.user_state
      # users_table: # schema.users
      # users__locations_table: # schema.users__locations
